In [1]:
%load_ext autoreload
%autoreload 2
import parse_data.prepare_data as prepare_data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import globals
import data_strings
import plotting.plot_octagon as plot_octagon
import plotting.plot_probability_chose_wall as plot_probability_chose_wall
import plotting.plot_trajectory as plot_trajectory
import analysis.wall_visibility_and_choice as wall_visibility_and_choice
import plotting.plot_probability_chose_wall as plot_probability_chose_wall
import data_extraction.trial_list_filters as trial_list_filters
from scipy.stats import norm
import data_extraction.data_saving as data_saving
import parse_data.identify_filepaths as identify_filepaths
import analysis.player_scores as player_scores

### Notebook to generate payment split based on player performance across solo and competitive sessions

- Pick a random string of n trials
  - player_scores.proportion_score_subset_sessions_df()
- Give a flat increase for winning social
  - player_scores.is_winner()
- Compare second solo scores
  - player_scores.proportion_score_solo_sessions_df()

In [55]:
loading = False
last_n_sessions = True
n = 5

In [45]:
weight_social = 0.7
weight_solo = 0.15
weight_winner = 0.15

In [46]:
# to load all data:
if loading:
    # load previously prepared data
    trial_lists_solo = data_saving.load_data(r'trial_lists_solo_combined_standard_50')
    trial_lists_social = data_saving.load_data(r'trial_lists_social_standard_50')

In [ ]:
2025-10-17_10-28-49_XL17_EV17_Social.json
2025-06-20_15-30-03_JK20_DD20_Social.json

In [ ]:
2025-06-20_15-18-58_JK20_FirstSolo.json
2025-10-17_10-16-46_XL17_FirstSolo.json
2025-10-17_10-17-01_EV17_FirstSolo.json
2025-10-17_10-50-57_EV17_SecondSolo.json
2025-10-17_10-51-05_XL17_SecondSolo.json

In [56]:
if not loading:
    data_folder = data_strings.DATA_FOLDER
    json_filenames_social, json_filenames_solo = identify_filepaths.get_filenames(data_folder=data_folder)
    test = identify_filepaths.get_relative_paths('Solo', data_folder=data_folder)

    if last_n_sessions:
        json_filenames_social = json_filenames_social[-n:]
        json_filenames_solo = json_filenames_solo[-n*4:]

print(json_filenames_solo)

_, trials_lists_solo = prepare_data.prepare_data(data_folder, json_filenames_solo, combine=False)
_, trials_lists_social = prepare_data.prepare_data(data_folder, json_filenames_social, combine=False)

['251013_1/2025-10-13_13-13-04_FA13_FirstSolo.json', '251013_1/2025-10-13_13-44-03_FA13_SecondSolo.json', '251013_1/2025-10-13_13-12-53_SW13_FirstSolo.json', '251013_1/2025-10-13_13-44-12_SW13_SecondSolo.json', '251013_2/2025-10-13_14-16-45_SW13_FirstSolo.json', '251013_2/2025-10-13_14-45-48_SW13_SecondSolo.json', '251013_2/2025-10-13_14-16-36_MU13_FirstSolo.json', '251013_2/2025-10-13_14-45-03_MU13_SecondSolo.json', '251015_1/2025-10-15_09-10-38_CS15_FirstSolo.json', '251015_1/2025-10-15_09-42-32_CS15_SecondSolo.json', '251015_1/2025-10-15_09-10-52_SK15_FirstSolo.json', '251015_1/2025-10-15_09-42-45_SK15_SecondSolo.json', '251017_1/2025-10-17_10-16-46_XL17_FirstSolo.json', '251017_1/2025-10-17_10-51-05_XL17_SecondSolo.json', '251017_1/2025-10-17_10-17-01_EV17_FirstSolo.json', '251017_1/2025-10-17_10-50-57_EV17_SecondSolo.json', '251017_2/2025-10-17_11-18-32_MZ17_FirstSolo.json', '251017_2/2025-10-17_11-50-05_MZ17_SecondSolo.json', '251017_2/2025-10-17_11-18-44_CW17_FirstSolo.json', '2

IntProgress(value=0, max=20)

filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-13-04_FA13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-44-03_FA13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-12-53_SW13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-44-12_SW13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-16-45_SW13_FirstSolo.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-45-48_SW13_SecondSolo.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-16-36_MU13_FirstSolo.json
Loading co

IntProgress(value=0, max=5)

filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_1/2025-10-13_13-23-15_FA13_SW13_Social.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251013_2/2025-10-13_14-27-33_SW13_MU13_Social.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251015_1/2025-10-15_09-21-08_CS15_SK15_Social.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251017_1/2025-10-17_10-28-49_XL17_EV17_Social.json
Loading complete.
Preprocessing complete.
filepath: /mnt/tom/ceph/ogma/human_octagon/RAW/standard/251017_2/2025-10-17_11-28-45_MZ17_CW17_Social.json
Loading complete.
Preprocessing complete.


In [64]:
json_filenames_social

['251013_1/2025-10-13_13-23-15_FA13_SW13_Social.json',
 '251013_2/2025-10-13_14-27-33_SW13_MU13_Social.json',
 '251015_1/2025-10-15_09-21-08_CS15_SK15_Social.json',
 '251017_1/2025-10-17_10-28-49_XL17_EV17_Social.json',
 '251017_2/2025-10-17_11-28-45_MZ17_CW17_Social.json']

In [65]:
proportion_scores_social_subset = player_scores.proportion_score_subset_sessions_df(trials_lists_social, num_trials=40, debug=False)

Session 0: total_trials=130, subset_length=40, start_index=38
Starting trial end scores -> player0: 710.0, player1: 820.0
Ending   trial end scores -> player0: 1860.0, player1: 1260.0
Accumulated scores -> player0: 1150.0, player1: 440.0
Accumulated total: 1590.0
Proportion accumulated total earned by player0: 0.7232704402515723
Session 1: total_trials=107, subset_length=40, start_index=52
Starting trial end scores -> player0: 920.0, player1: 1280.0
Ending   trial end scores -> player0: 1610.0, player1: 2030.0
Accumulated scores -> player0: 690.0, player1: 750.0
Accumulated total: 1440.0
Proportion accumulated total earned by player0: 0.4791666666666667
Session 2: total_trials=137, subset_length=40, start_index=16
Starting trial end scores -> player0: 400.0, player1: 300.0
Ending   trial end scores -> player0: 1400.0, player1: 890.0
Accumulated scores -> player0: 1000.0, player1: 590.0
Accumulated total: 1590.0
Proportion accumulated total earned by player0: 0.6289308176100629
Session 

In [60]:
proportion_scores_social_subset

array([[0.74404762, 0.25595238],
       [0.4822695 , 0.5177305 ],
       [0.6918239 , 0.3081761 ],
       [0.69934641, 0.30065359],
       [0.73856209, 0.26143791]])

In [67]:
is_winner = player_scores.is_winner(trials_lists_social, debug=False)

In [68]:
# player0 and player1 second solos. Use index [1::2] to get all second solos in one list
trials_lists_player0 = trials_lists_solo[1::4]
trials_lists_player1 = trials_lists_solo[3::4]

In [69]:
solo_proportion_scores = player_scores.proportion_score_solo_sessions_df(trials_lists_player0, trials_lists_player1, debug=False)

In [70]:
proportion_scores_social_subset, solo_proportion_scores, is_winner

(array([[0.72327044, 0.27672956],
        [0.47916667, 0.52083333],
        [0.62893082, 0.37106918],
        [0.75      , 0.25      ],
        [0.46783626, 0.53216374]]),
 array([[0.50272232, 0.49727768],
        [0.49667774, 0.50332226],
        [0.47282609, 0.52717391],
        [0.50195312, 0.49804688],
        [0.51538462, 0.48461538]]),
 array([[1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]))

In [71]:

final_array = proportion_scores_social_subset*weight_social + solo_proportion_scores*weight_solo + is_winner*weight_winner

In [72]:
final_array

array([[0.73169766, 0.26830234],
       [0.40991833, 0.59008167],
       [0.66117549, 0.33882451],
       [0.75029297, 0.24970703],
       [0.55479307, 0.44520693]])